In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import itertools
import os
import pandas as pd
import sys
path_to_package = '/'.join(os.getcwd().split('/')[:-1])
sys.path.append(path_to_package)

In [ ]:
df = pd.read_csv('../data/close.csv', index_col=0)
df = df.iloc[-50:, :3]

window = 4
corr = df.rolling(window).cov()

columns = ['{}/{}'.format(m, n) for (m, n) in itertools.product(df.columns, repeat=2)]

corr_flattened = pd.DataFrame(index=columns).transpose()

for i in range(df.shape[0]):

    data = corr[df.shape[1]*i : df.shape[1]*(i+1)].to_numpy().flatten()
    index = [corr.index[df.shape[1]*i][0]]

    temp = pd.DataFrame(data=data, columns=index, index=columns).transpose()
    corr_flattened = pd.concat([corr_flattened, temp])

corr_flattened.tail()

In [ ]:
def append_corr_matrix(df: pd.DataFrame,
                       window: int,
                       ) -> pd.DataFrame:
    """
        Computes the sliding correlation matrix of a multidimensional time series, \ 
        timewise flattens it and extracts just the upper triangular part (since it is symmetric), \
        then appends it to the initial time series.
    """

    columns = ['{}/{}'.format(m, n) for (m, n) in itertools.combinations_with_replacement(df.columns, r=2)]
    corr = df.rolling(window).cov()
    corr_flattened = pd.DataFrame(index=columns).transpose()

    for i in range(window-1, df.shape[0]):

        ind = np.triu_indices(df.shape[1])
        data = corr[df.shape[1]*i : df.shape[1]*(i+1)].to_numpy()[ind]
        index = [corr.index[df.shape[1]*i][0]]

        temp = pd.DataFrame(data=data, columns=index, index=columns).transpose()
        corr_flattened = pd.concat([corr_flattened, temp])

    return pd.concat([df.iloc[window-1 : ], corr_flattened], axis=1)

In [ ]:
def append_corr_matrix2(df: pd.DataFrame,
                       window: int,
                       ) -> pd.DataFrame:
    """
        Computes the sliding correlation matrix of a multidimensional time series, \ 
        timewise flattens it and extracts just the upper triangular part (since it is symmetric), \
        then appends it to the initial time series.
    """

    columns = ['{}/{}'.format(m, n) for (m, n) in itertools.combinations_with_replacement(df.columns, r=2)]
    corr = df.rolling(window).cov()
    corr_flattened = pd.DataFrame(index=columns).transpose()

    for i in range(df.shape[0]):

        ind = np.triu_indices(df.shape[1])
        data = corr[df.shape[1]*i : df.shape[1]*(i+1)].to_numpy()[ind]
        index = [corr.index[df.shape[1]*i][0]]

        temp = pd.DataFrame(data=data, columns=index, index=columns).transpose()
        corr_flattened = pd.concat([corr_flattened, temp])

    return pd.concat([df, corr_flattened], axis=1).iloc[window-1 : ]

In [ ]:
corr_flattened = append_corr_matrix(df, 4)
corr_flattened2 = append_corr_matrix2(df, 4)
print(corr_flattened.index)
print(corr_flattened2.index)

In [ ]:
df = pd.read_csv('../data/close.csv', index_col=0)
df = df.iloc[-50:, :3]

window = 4

columns = ['Eigenvalue_{}'.format(m+1) for m in range(2)]
corr = df.rolling(window).cov()
corr_flattened = pd.DataFrame(index=columns).transpose()

for i in range(window-1, df.shape[0]):
    ind = np.triu_indices(df.shape[1])
    data = corr[df.shape[1]*i : df.shape[1]*(i+1)].to_numpy()
    data = np.linalg.eig(data)
    data = data[0]
    data[::-1].sort()
    data = data[:2]

    index = [corr.index[df.shape[1]*i][0]]
    temp = pd.DataFrame(data=data, columns=index, index=columns).transpose()
    corr_flattened = pd.concat([corr_flattened, temp])

pd.concat([df.iloc[window-1 : ], corr_flattened], axis=1)


In [ ]:
def append_corr_matrix_eigenvalues(df: pd.DataFrame,
                                   window: int,
                                   k: int = 10
                                   ) -> pd.DataFrame:
    
    columns = ['Eigenvalue_{}'.format(m+1) for m in range(k)]
    corr = df.rolling(window).cov()
    corr_eigenvalues = pd.DataFrame(index=columns).transpose()

    for i in range(window-1, df.shape[0]):
        data = corr[df.shape[1]*i : df.shape[1]*(i+1)].to_numpy()
        data = np.linalg.eig(data)
        data = data[0]
        data[::-1].sort()
        data = data[:k]

        index = [corr.index[df.shape[1]*i][0]]
        temp = pd.DataFrame(data=data, columns=index, index=columns).transpose()
        corr_eigenvalues = pd.concat([corr_eigenvalues, temp])

    return pd.concat([df.iloc[window-1 : ], corr_eigenvalues], axis=1)

In [ ]:
df = pd.read_csv('../data/close.csv', index_col=0)

In [ ]:
df.columns.shape

In [ ]:
with open("./tickers_S&P500.txt", "r") as file:
    lines = file.readlines()
    a = []
    for l in lines:
	    a.append(l.replace("\n", ""))

In [ ]:
initial_number_of_shares = {key: 0 for key in a}

In [ ]:
import json

In [ ]:
with open("./initial_portfolio.json", "w") as file:
    file = json.dump(initial_number_of_shares, file)

In [13]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [18]:
reward_history = np.load("../saved_outputs/2021.07.23.14.10.51/logs/reward_history.npy")
portfolio_value_history = np.load("../saved_outputs/2021.07.23.14.10.51/logs/portfolio_value_history.npy")

In [21]:
portfolio_value_history.shape

(2, 1133)

In [4]:
a = np.load('../saved_outputs/2021.07.24.23.35.30/logs/train_reward_history.npy')

In [7]:
a

array([-1781.36702073, -1087.07777719,   794.85202478,  2148.68619929,
        1368.92762171,  1429.18426939,  1634.23469595,  1383.7153149 ,
         796.82555529, -1811.02160287, -1401.41648666,  1629.895154  ,
        1544.86718447,   754.62028372,  -405.71290236])

In [8]:
i = 100000

In [10]:
(i + a) / i

array([0.98218633, 0.98912922, 1.00794852, 1.02148686, 1.01368928,
       1.01429184, 1.01634235, 1.01383715, 1.00796826, 0.98188978,
       0.98598584, 1.01629895, 1.01544867, 1.0075462 , 0.99594287])